// Generated by tools/svg2mod_frames.py from the v2 SVG frames. Do not edit.
import type { V2Anim } from './types'

// beacon: 16 source frames -> 9 stored, 32x38 art px
export const anim: V2Anim = {
  fps: 8,
  width: 32,
  height: 38,
  palette: ['#DE886D', '#6B3122', '#B8644B', '#F3AC90', '#1B1B1B', '#202020', '#1B1311', '#6B737D', '#FF5A5F', '#A9B2BC', '#3D8BFD', '#FFC93C', '#DCE2E8', '#FFD3C2', '#FFFFFF', '#FFA3A6', '#9CC4FF', '#FFE9A3'],
  frames: [
    ['//////.15qk/.15k2//.12qk.pi.qk/.12k2.i2.k2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 4],
    ['///////.15qk/.15k2//.12qk.4qk/.12k2.4k2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 1],
    ['////.15rl/.15l2//.15qk/.15k2//.9rl.qk.4qk.rl/.9l2.k2.4k2.l2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 1],
    ['////.15rl/.15l2/////.9rl.10rl/.9l2.10l2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 1],
    ['////.15rl/.15l2/////.9rl.4pi.4rl/.9l2.4i2.4l2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 3],
    ['/.15pi/.15i2//.15rl/.15l2/////.6pi.rl.10rl.pi/.6i2.l2.10l2.i2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 1],
    ['/.15pi/.15i2////////.6pi.16pi/.6i2.16i2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 1],
    ['.15pi/.15i2////////.6pi.16pi/.6i2.16i2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 1],
    ['.15pi/.15i2////////.6pi.7pi.7pi/.6i2.7i2.7i2//.15jh/.15mh/.15mh/.15jh/.15jh/.15jh/.5b22/.5bd19ab/.5bdn2a16cb/.b5da18cb5/bcd5a2oga10oga2cd4cb/b2ca3da2g2a10g2a2ca3cb2/.2ba3da2g2a10g2a2ca3b/.2ba3da2g2a10g2a2ca3b/b2da3da18ca3db2/bc5da18c6b/.b5da18cb5/.5bac19b/.5bac19b/.5b22/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7cb.2cb.6cb.2cb/.7b2.2b2.6b2.2b2/.4e24/.7f18', 3],
  ],
}
