// Generated by tools/svg2mod_frames.py. Do not edit.
import type { AnimName } from '../../types'
import { anim as v2_idle } from './idle'
import { anim as v2_sleeping } from './sleeping'
import { anim as v2_low_battery } from './low_battery'
import { anim as v2_hat_mishap } from './hat_mishap'
import { anim as v2_thinking } from './thinking'
import { anim as v2_typing } from './typing'
import { anim as v2_debugger } from './debugger'
import { anim as v2_building } from './building'
import { anim as v2_conducting } from './conducting'
import { anim as v2_waiting_reply } from './waiting_reply'
import { anim as v2_wake } from './wake'
import { anim as v2_confused } from './confused'
import { anim as v2_dizzy } from './dizzy'
import { anim as v2_sweeping } from './sweeping'
import { anim as v2_beacon } from './beacon'
import { anim as v2_happy } from './happy'
import { anim as v2_alert } from './alert'
import type { V2Anim } from './types'

// AnimName -> v2 art; names missing here fall back to the v1 pose functions.
export const ANIMS_V2: Partial<Record<AnimName, V2Anim>> = {
  idle: v2_idle,
  sleeping: v2_sleeping,
  low_battery: v2_low_battery,
  hat_mishap: v2_hat_mishap,
  thinking: v2_thinking,
  typing: v2_typing,
  debugger: v2_debugger,
  building: v2_building,
  conducting: v2_conducting,
  waiting_reply: v2_waiting_reply,
  wake: v2_wake,
  confused: v2_confused,
  dizzy: v2_dizzy,
  sweeping: v2_sweeping,
  beacon: v2_beacon,
  happy: v2_happy,
  alert: v2_alert,
  idle_living: v2_idle,
}

// Widest and tallest v2 animation, in art pixels (columns / pixel rows).
export const V2_MAX_WIDTH = 57
export const V2_MAX_HEIGHT = 50
