// Generated by tools/svg2mod_frames.py from the v2 SVG frames. Do not edit.
import type { V2Anim } from './types'

// low_battery: 48 source frames -> 11 stored, 34x32 art px
export const anim: V2Anim = {
  fps: 6,
  width: 34,
  height: 32,
  palette: ['#DE886D', '#6B3122', '#2A1E1A', '#B8644B', '#FF4444', '#7A1F1F', '#F3AC90', '#1B1B1B', '#202020', '#1B1311', '#FFD3C2'],
  frames: [
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18//////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8db.2db.6db.2db/.8b2.2b2.6b2.2b2/.5h24/.8i18', 5],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18///////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8b2.2b2.6b2.2b2/.5h24/.8i18', 5],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18////////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.5h24/.8i18', 5],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18///////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8b2.2b2.6b2.2b2/.5h24/.8i18', 5],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18//////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8db.2db.6db.2db/.8b2.2b2.6b2.2b2/.5h24/.8i18', 9],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18///////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8b2.2b2.6b2.2b2/.5h24/.8i18', 4],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18///////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga3j2a10j2a3da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8b2.2b2.6b2.2b2/.5h24/.8i18', 1],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18////////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga3j2a10j2a3da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.5h24/.8i18', 5],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18///////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga3j2a10j2a3da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8b2.2b2.6b2.2b2/.5h24/.8i18', 2],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18///////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8b2.2b2.6b2.2b2/.5h24/.8i18', 3],
    ['/.9f18/.8fe18f/.8fec16e2f2/.8fece3c12e3f/.8fece3c12e3f/.8fece3c12e3f/.8fec16e2f2/.8fe18f/.9f18//////.5b24/.5bg21ab/.5bgk2a18db/.5bga20db/.b5ga20db5/bdg5a3j2a10j2a3dg4db/b2da3ga20da3db2/.2ba3ga20da3b/.2ba3ga20da3b/b2ga3ga20da3gb2/bd5ad26b/.b5ad21b5/.5b24/.8db.2db.6db.2db/.8b2.2b2.6b2.2b2/.5h24/.8i18', 4],
  ],
}
