// Generated by tools/svg2mod_frames.py from the v2 SVG frames. Do not edit.
import type { V2Anim } from './types'

// sweeping: 12 source frames -> 12 stored, 45x26 art px
export const anim: V2Anim = {
  fps: 8,
  width: 45,
  height: 26,
  palette: ['#DE886D', '#6B3122', '#B8644B', '#F3AC90', '#1B1B1B', '#6E4A0C', '#202020', '#93603E', '#5C3922', '#1B1311', '#C98918', '#FFDB6E', '#9E9E9E', '#FFD3C2', '#B0BEC5', '#FFFFFF'],
  frames: [
    ['/.24hi/.24hi/.24hi/.24hi/.2b22hi/.2bd19cbhi/.2bn2a17chi/.bda18cb5/.bda14pja2cd4cb/.bda14j2a2ca3cb2/.bda2j2a2b5a3j2a2ca3b/.bda2j2abcd3ba3j2a2ca3b/.bda5b2ca2ba7ca3db2/.bda7ba2ba7c6b/.bda7ba2ba7cb5/bc7b2da2bc7bhi/bc7bc4bc7bhi/b21hi/.2cb.2cb.6cb.2cb.hi/.2cb.2cb.6cb.2cb.hi/.2cb.2cb.6cb.2f6.14o2.m2/.2b2.2b2.6b2.2fl5f2.12o2.m2/e18fk5lf/.3g15f7/.23f2', 1],
    ['//.25hi/.24hi/.24hi/.2b22hi/.2bd19cbhi/.2bn2a17cbhi/.bda18cb5/.bda14pja2cd4cb/.bda14j2a2ca3cb2/.bda2j2a2b5a3j2a2ca3b/.bda2j2abcd3ba3j2a2ca3b/.bda5b2ca2ba7ca3db2/.bda7ba2ba7c6b/.bda7ba2ba7cb5/bc7b2da2bc7bhi/bc7bc4bc7bhi/b21h2i/.2cb.2cb.6cb.2cb.hi/.2cb.2cb.6cb.2cb.hi/.2cb.2cb.6cb.2f6.16o.2m2/.2b2.2b2.6b2.2fl4f3.17m2/e17fk5l2f/.3g15f5kf/.23f2', 1],
    ['//.27hi/.27hi/.26hi/.3b22.hi/.3bd19cb.hi/.3bn2a17b5/.2bda18cd4cb/.2bda14pja2ca3cb2/.2bda14j2a2ca3b/.2bda2j2a2b5a3j2a2ca3b/.2bda2j2abcd3ba3j2a2ca3db2/.2bda5b2ca2ba7c6b/.2bda7ba2ba7cb5/.2bda7ba2ba7ch2i/.bc7b2da2bc7bhi/.bc7bc4bc7bhi/.b22hi/.3cb.2cb.6cb.2cb.hi/.3cb.2cb.6cb.2fb.hi/.3cb.2cb.6cb.2f5.18o/.3b2.2b2.6b2.f2l4f3/e18f2k4lf2/.3g17f3k2f/.23f3', 1],
    ['/.30h/.29hi/.29hi/.29hi/.5b22.hi/.5bd19cb.hi/.5bn2a17b5/.4bda18cd4cb/.4bda14pja2ca3cb2/.4bda14j2a2ca3b/.4bda2j2a2b5a3j2a2ca3b/.4bda2j2abcd3ba3j2a2ca3db2/.4bda5b2ca2ba7c6b/.4bda7ba2ba7cb5/.4bda7ba2ba7chi/.3bc7b2da2bc7hi/.3bc7bc4bc7hi/.3b21hi/.4cb.2cb.6cb.2f2.hi/.4cb.2cb.6cb.2f4i/.4cb.2cb.6cb.fkl3f3.17o/.4b2.2b2.6b2.f2k3l2f/e21f3k2f/.3g20.f3/', 1],
    ['/.32hi/.32hi/.31hi/.31hi/.30hi2/.7b22.hi/.7bd18cb5/.7bn2a15b3d3cb/.5b2da17d3a2cb2/.5bda14pja7b/.5bda14j2a7b/.5bda2j2a2b5a3j2a2c3a2db2/.5bda2j2abcd3ba3j2a2b3c4b/.5bda5b2ca2ba7chb5/.5bda7ba2ba7chi/.5bda7ba2ba7hi/.4bc7b2da2bc7hi/.4bc7bc4bc3f2chi/.4b16f2lf2i/.5cb.2cb.6cb.fkl3f2/.5cb.2cb.6cb.f2k3l2f/.5b2.2b2.6b2.2bf2k3f/e24f3/.3g20.3f/', 1],
    ['//.34hi/.34hi/.33hi/.32h2i/.8b26/.8bd18b3d3cb/.8bn2a16d3a2cb2/.7bda23b/.7bda14pja7b/.7bda14j2a2c3a2db2/.7bda2j2a2b5a3j2a2b3c4b/.7bda2j2abcd3ba3j2a2chb5/.7bda5b2ca2ba7h2i/.7bda7ba2ba6chi/.7bda7ba2ba6h2i/.5b2c7b2da2bc6hi/.5bc8bc4bc2f2chi2/.5b16fl2f2i/.6cb.2cb.6cb.fk2l2f2/.6cb.2cb.6cb.f2k2l2f2/.6b2.2b2.6b2.2bf2k2lf/e25f3/.3g20.4f/', 1],
    ['//.35h/.34hi/.33h2i/.33hi/.9b25i/.9bd17b3d3cb/.9bn2a15d3a2cb2/.7b2da22b/.7bda14pja7b/.7bda14j2a2c3a2db2/.7bda2j2a2b5a3j2a2b3c4b/.7bda2j2abcd3ba3j2a2chb5/.7bda5b2ca2ba7chi/.7bda7ba2ba6chi/.7bda7ba2ba6h2i/.5b2c7b2da2bc6hi/.5bc8bc4bc2f2chi2/.5b16fl2f2i/.6cb.2cb.6cb.fk2l2f2/.6cb.2cb.6cb.f2k2l2f2/.6b2.2b2.6b2.2bf2k2lf/e25f3/.3g20.4f/', 1],
    ['//.34hi/.34hi/.33hi/.32h2i/.8b26/.8bd18b3d3cb/.8bn2a16d3a2cb2/.7bda23b/.7bda14pja7b/.7bda14j2a2c3a2db2/.7bda2j2a2b5a3j2a2b3c4b/.7bda2j2abcd3ba3j2a2chb5/.7bda5b2ca2ba7h2i/.7bda7ba2ba6chi/.7bda7ba2ba6h2i/.5b2c7b2da2bc6hi/.5bc8bc4bc2f2chi2/.5b16fl2f2i/.6cb.2cb.6cb.fk2l2f2/.6cb.2cb.6cb.f2k2l2f2.m2/.6b2.2b2.6b2.2bf2k2lf.m2/e25f3/.3g20.4f/', 1],
    ['/.32hi/.32hi/.31hi/.31hi/.30hi2/.7b22.hi/.7bd18cb5/.7bn2a15b3d3cb/.5b2da17d3a2cb2/.5bda14pja7b/.5bda14j2a7b/.5bda2j2a2b5a3j2a2c3a2db2/.5bda2j2abcd3ba3j2a2b3c4b/.5bda5b2ca2ba7chb5/.5bda7ba2ba7chi/.5bda7ba2ba7hi/.4bc7b2da2bc7hi/.4bc7bc4bc3f2chi/.4b16f2lf2i/.5cb.2cb.6cb.fkl3f2/.5cb.2cb.6cb.f2k3l2f.5m3/.5b2.2b2.6b2.2bf2k3f.5m3/e24f3.6m3/.3g20.3f/', 1],
    ['/.30h/.29hi/.29hi/.29hi/.5b22.hi/.5bd19cb.hi/.5bn2a17b5/.4bda18cd4cb/.4bda14pja2ca3cb2/.4bda14j2a2ca3b/.4bda2j2a2b5a3j2a2ca3b/.4bda2j2abcd3ba3j2a2ca3db2/.4bda5b2ca2ba7c6b/.4bda7ba2ba7cb5/.4bda7ba2ba7chi/.3bc7b2da2bc7hi/.3bc7bc4bc7hi/.3b21hi/.4cb.2cb.6cb.2f2.hi/.4cb.2cb.6cb.2f4i/.4cb.2cb.6cb.fkl3f3.4o2.2m3/.4b2.2b2.6b2.f2k3l2f.4o2.2m3/e21f3k2f.8m3/.3g20.f3/', 1],
    ['//.27hi/.27hi/.26hi/.3b22.hi/.3bd19cb.hi/.3bn2a17b5/.2bda18cd4cb/.2bda14pja2ca3cb2/.2bda14j2a2ca3b/.2bda2j2a2b5a3j2a2ca3b/.2bda2j2abcd3ba3j2a2ca3db2/.2bda5b2ca2ba7c6b/.2bda7ba2ba7cb5/.2bda7ba2ba7ch2i/.bc7b2da2bc7bhi/.bc7bc4bc7bhi/.b22hi/.3cb.2cb.6cb.2cb.hi/.3cb.2cb.6cb.2fb.hi/.3cb.2cb.6cb.2f5.10o2.m2/.3b2.2b2.6b2.f2l4f3.7o2.m2/e18f2k4lf2/.3g17f3k2f/.23f3', 1],
    ['//.25hi/.24hi/.24hi/.2b22hi/.2bd19cbhi/.2bn2a17cbhi/.bda18cb5/.bda14pja2cd4cb/.bda14j2a2ca3cb2/.bda2j2a2b5a3j2a2ca3b/.bda2j2abcd3ba3j2a2ca3b/.bda5b2ca2ba7ca3db2/.bda7ba2ba7c6b/.bda7ba2ba7cb5/bc7b2da2bc7bhi/bc7bc4bc7bhi/b21h2i/.2cb.2cb.6cb.2cb.hi/.2cb.2cb.6cb.2cb.hi/.2cb.2cb.6cb.2f6.12o2.m2/.2b2.2b2.6b2.2fl4f3.10o2.m2/e17fk5l2f/.3g15f5kf/.23f2', 1],
  ],
}
