// Generated by tools/svg2mod_frames.py from the v2 SVG frames. Do not edit.
import type { V2Anim } from './types'

// typing: 12 source frames -> 12 stored, 41x38 art px
export const anim: V2Anim = {
  fps: 8,
  width: 41,
  height: 38,
  palette: ['#DE886D', '#8696A3', '#2B343B', '#6B3122', '#F3AC90', '#40C4FF', '#B8644B', '#A9B8C4', '#202020', '#5F6F7B', '#31657D', '#1B1311', '#3585A8', '#FFFFFF', '#BDEFFF', '#1B1B1B', '#FFD3C2', '#63777D', '#809EA8'],
  frames: [
    ['/////.38sm2/.28rk2.7m3/.28k3.3sm2.m3/.28k3.3m3/.34m3/////////.8d22/.8de19ad/.8deq2a16gd/.4d5ea18gd/.3dge5a18gd/.3d2ga3el2a10l2a4gd/.5da3el2a10l2a4gd5/.5da3ec18ge4gd/.3d2ea3ech16cga3gd2/.3dg5echb15cga3d/.4d5echb5f4b6cga3d/.8dachb5fn2fb6cga3ed2/rk2.5dachb5fn2fb6cg6d/k3.5d2chb5f4b6cd6/k3.7chb15c/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['//.38rk2/.38k3/.34rk2.k3/.34k3/.34k3/////////////.8d22/.8de19ad/.8deq2a16gd/.8dea18gd5/.8dea18ge4gd/.8del2a10l2a4ga3gd2/.4d5ec18ga3d/of2dge5ch16cga3d/f3d2ga3echb15cga3ed2/f3.2da3echb5f4b6cg6d/.5da3echb5fn2fb6cgd5/.3d2ea4chb5fn2fb6cgd/.3dg5achb5f4b6cgd/.4d6chb15cd2/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['//////////////////.8d22/.8de19ad/.8deq2a16gd/.4d5ea18gd/of2dge5a18gd/f3d2ga3eal2a10l2a3gd/f3.2da3eal2a10l2a3gd5/.5da3ec18ge4gd/.3d2ea3ech16cga3gd2/.3dg5echb15cga3d/.4d5echb5f4b6cga3d/.8dachb5fn2fb6cga3ed2/.8dachb5fn2fb6cg6d/.8d2chb5f4b6cd6/.10chb15c/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['//////////////////.20of2/of2.5d22/f3.5de19ad/f3.5deq2a16gd/.8dea18gd5/.8dea18ge4gd/.8deal2a10l2a3ga3gd2/.4d5ec18ga3d/.3dge5ch16cga3d/.3d2ga3echb15cga3ed2/.5da3echb5f4b6cg6d/.5da3echb5fn2fb6cgd5/.3d2ea4chb5fn2fb6cgd/.3dg5achb5f4b6cgd/.4d6chb15cd2/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['///////////////of2.17of2/f3.17f3/f3.17f3/.8d22/.8de19ad/.8deq2a16gd/.4d5ea18gd/.3dge5a18gd/.3d2ga3ea2l2a10l2a2gd/.5da3ea2l2a10l2a2gd5/.5da3ec18ge4gd/.3d2ea3ech16cga3gd2/.3dg5echb15cga3d/.4d5echb5f4b6cga3d/.8dachb5fn2fb6cga3ed2/.8dachb5fn2fb6cg6d/.8d2chb5f4b6cd6/.10chb15c/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['///////////of2.17of2/f3.17f3/f3.17f3////.14of2/.14f3/.8d22/.6ofde19ad/.6f2deq2a16gd/.6f2dea18gd5/.8dea18ge4gd/.8dea2l2a10l2a2ga3gd2/.4d5ec18ga3d/.3dge5ch16cga3d/.3d2ga3echb15cga3ed2/.5da3echb5f4b6cg6d/.5da3echb5fn2fb6cgd5/.3d2ea4chb5fn2fb6cgd/.3dg5achb5f4b6cgd/.4d6chb15cd2k/.10cj16ck3/.10c18k3/.8cb20c/.7pc22p/.10i18', 1],
    ['///////sm2.17of2/m3.17f3/m3.17f3////.14of2/.14f3/.14f3//.6of2/.6f2d22/.6f2de19ad/.8deq2a16gd/.4d5ea18gd/.3dge5a18gd/.3d2ga3ea3l2a10l2agd/.5da3ea3l2a10l2agd5/.5da3ec18ge4gd/.3d2ea3ech16cga3gd2/.3dg5echb15cga3d/.4d5echb5f4b6cga3d.5rk2/.8dachb5fn2fb6cga3ed2.3k3/.8dachb5fn2fb6cg6dk2.k3/.8d2chb5f4b6cd6k3/.10chb15c.6k3/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['///.20sm2/rk2.17m3/k3.17m3/k3///.14of2/.14f3/.14f3//.6of2/.6f3/.6f3////.8d22/.8de19ad/.8deq2a16gd/.8dea18gd5/.8dea18ge4gd/.8dea3l2a10l2aga3gd2.3of2/.4d5ec18ga3d.5f3/.3dge5ch16cga3d.of2.f3/.3d2ga3echb15cga3ed2f2/.5da3echb5f4b6cg6df2/.5da3echb5fn2fb6cgd5/.3d2ea4chb5fn2fb6cgd/.3dg5achb5f4b6cgd/.4d6chb15cd2/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['.20rk2/.20k3/.20k3///.14sm2/.14m3/.14m3//.6of2/.6f3/.6f3///////.8d22/.8de19ad/.8deq2a16gd.8of2/.4d5ea18gdf.7f3/.3dge5a18gdf.3of2.f3/.3d2ga3ea4l2a10l2gdf.3f3/.5da3ea4l2a10l2gd5f3/.5da3ec18ge4gd/.3d2ea3ech16cga3gd2/.3dg5echb15cga3d/.4d5echb5f4b6cga3d/.8dachb5fn2fb6cga3ed2/.8dachb5fn2fb6cg6d/.8d2chb5f4b6cd6/.10chb15c/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['//.14rk2/.14k3/.14k3/.6sm2/.6m3/.6m3//////////.28of2.7of2/.28f3.7f3/.8d22f.3of2.f3/.8de19ad.4f3/.8deq2a16gd.4f3/.8dea18gd5/.8dea18ge4gd/.8dea4l2a10l2ga3gd2/.4d5ec18ga3d/.3dge5ch16cga3d/.3d2ga3echb15cga3ed2/.5da3echb5f4b6cg6d/.5da3echb5fn2fb6cgd5/.3d2ea4chb5fn2fb6cgd/.3dg5achb5f4b6cgd/.4d6chb15cd2/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['//.6rk2/.6k3/.6k3/////////.28of2.7of2/.28f3.7f3/.28f3.3of2.f3/.34f3/.34f3/.8d22/.8de19ad/.8deq2a16gd/.4d5ea18gd/.3dge5a18gd/.3d2ga3ea4l2a10l2gd/.5da3ea4l2a10l2gd5/.5da3ec18ge4gd/.3d2ea3ech16cga3gd2/.3dg5echb15cga3d/.4d5echb5f4b6cga3d/.8dachb5fn2fb6cga3ed2/.8dachb5fn2fb6cg6d/.8d2chb5f4b6cd6/.10chb15c/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
    ['/////////.28sm2.7of2/.28m3.7f3/.28m3.3of2.f3/.34f3/.34f3//////.8d22/.8de19ad/.8deq2a16gd/.8dea18gd5/.8dea18ge4gd/.8del2a10l2a4ga3gd2/.4d5ec18ga3d/.3dge5ch16cga3d/.3d2ga3echb15cga3ed2/.5da3echb5f4b6cg6d/.5da3echb5fn2fb6cgd5/.3d2ea4chb5fn2fb6cgd/.3dg5achb5f4b6cgd/.4d6chb15cd2/.10cj16c/.10c18/.8cb20c/.7pc22p/.10i18', 1],
  ],
}
