// Generated by tools/svg2mod_frames.py from the v2 SVG frames. Do not edit.
import type { V2Anim } from './types'

// wake: 12 source frames -> 9 stored, 36x32 art px
export const anim: V2Anim = {
  fps: 8,
  width: 36,
  height: 32,
  palette: ['#DE886D', '#6B3122', '#B8644B', '#F3AC90', '#1B1B1B', '#1B1311', '#202020', '#FFD3C2', '#FFFFFF'],
  frames: [
    ['////////////////////.5b26/.b5d23ab5/bcd5h2a20cd4cb/b2ca3da22ca3cb2/.2ba3da22ca3b/.2ba3da3f4a8f4a3ca3b/b2da3da22ca3db2/bc5ac28b/.b5ac23b5/.5b26/.e34/.4g28', 1],
    ['////////////////////.5b26/.b5d23ab5/bcd5h2a20cd4cb/b2ca3da22ca3cb2/.2ba3da3if3a8if3a3ca3b/.2ba3da3f4a8f4a3ca3b/b2da3da3f4a8f4a3ca3db2/bc5ac3f4c8f4c9b/.b5ac23b5/.5b26/.4e28/.7g22', 1],
    ['/////////.5b22/.5bcd18cb/.2b5ha17cb6/.bcd5a18cd4cb/.b2ca3da2ifa10ifa2ca3cb2/.3ba3da2f2a10f2a2ca3b/.3ba3da2f2a10f2a2ca3b/.b2da3da2f2a10f2a2ca3db2/.bc6a18c6b/.2b5ca18cb5/.7bc20b/.7bc20b/.7b22/.9b2.2b2.6b2.2b2////////.7e22/.10g16', 1],
    ['////.5b22/.5bcd18cb/.5bh2a17cb/.6bda18cb/.2b5da2ifa10ifa2cb5/.bcd5a2f2a10f2a2cd4cb/.b2ca3da2f2a10f2a2ca3cb2/.3ba3da2f2a10f2a2ca3b/.3ba3da18ca3b/.b2da3da18ca3db2/.bc5da18c6b/.2b5ca18cb5/.6bca18cb/.7bc20b/.7bc20b/.7b22/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9b2.2b2.6b2.2b2///////.9e18/.12g12', 1],
    ['.9b20/.9bd17cb/.9bh2a15cb/.9bda16cb/.5b5daifa10ifacb5/.4bcd5af2a10f2acd4cb/.4b2ca3daf2a10f2aca3cb2/.6ba3daf2a10f2aca3b/.6ba3da16ca3b/.4b2da3da16ca3db2/.4bc5da16c6b/.5b5da16cb5/.9bda16cb/.9bda16cb/.8bc18b/.8bc18b/.8b20/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9b2.2b2.6b2.2b2/////////.11e14/.14g8', 1],
    ['////.8b20/.8bd17ab/.8bdh2a14cb/.8bda16cb/.4b5daifa10ifacb5/.3bcd5af2a10f2acd4cb/.3b2ca3daf2a10f2aca3cb2/.5ba3daf2a10f2aca3b/.5ba3da16ca3b/.3b2da3da16ca3db2/.3bc5da16c6b/.4b5da16cb5/.8bda16cb/.8bac17b/.8bac17b/.8b20/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9b2.2b2.6b2.2b2//////.10e16/.13g10', 1],
    ['////////.6b22/.6bcd18cb/.6bh2a17cb/.3b5da18cb5/.2bcd5a2ifa10ifa2cd4cb/.2b2ca3da2f2a10f2a2ca3cb2/.4ba3da2f2a10f2a2ca3b/.4ba3da2f2a10f2a2ca3b/.2b2da3da18ca3db2/.2bc5da18c6b/.3b5da18cb5/.7bda18cb/.7bc20b/.7bc20b/.7b22/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9b2.2b2.6b2.2b2////.9e18/.12g12', 1],
    ['///////////.7b22/.7bd19ab/.7bdh2a16cb/.3b5da18cb5/.2bcd5a18cd4cb/.2b2ca3da18ca3cb2/.4ba3da2f2a10f2a2ca3b/.4ba3da18ca3b/.2b2da3da18ca3db2/.2bc5da18c6b/.3b5da18cb5/.7bac19b/.7bac19b/.7b22/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9b2.2b2.6b2.2b2//.9e18/.12g12', 1],
    ['////////////.7b22/.7bd19ab/.7bdh2a16cb/.3b5da18cb5/.2bcd5a2ifa10ifa2cd4cb/.2b2ca3da2f2a10f2a2ca3cb2/.4ba3da2f2a10f2a2ca3b/.4ba3da2f2a10f2a2ca3b/.2b2da3da18ca3db2/.2bc5da18c6b/.3b5da18cb5/.7bac19b/.7bac19b/.7b22/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9cb.2cb.6cb.2cb/.9b2.2b2.6b2.2b2/.9e18/.12g12', 4],
  ],
}
