#!/usr/bin/env python3
"""
Generate the app icon and the Windows tray icons from the Clawd crab pixel art.

The crab is the 15x9 pixel grid of assets/svg-animations/clawd-static-base.svg
(ground shadow excluded). Every output is rendered with nearest-neighbor
integer scaling so the pixels stay crisp, and the output is deterministic.

Outputs:
  assets/AppIcon.iconset/icon_*.png   app icon, every size the iconset carries
  assets/AppIcon.icns                 macOS app icon
  assets/app-icon.svg                 vector version of the 1024px app icon
  host/clawd_tank_menubar/icons/win-crab-*.png
                                      colored 32x32 Windows tray icons

The macOS tray keeps its monochrome template icons (icons/crab-*.png); they
are not generated here. host/windows/margarita_tank.spec builds the Windows
.ico from icon_256x256.png at build time.

Usage:
    python tools/gen_app_icons.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

REPO_ROOT = Path(__file__).parent.parent
ICONSET_DIR = REPO_ROOT / "assets" / "AppIcon.iconset"
ICNS_PATH = REPO_ROOT / "assets" / "AppIcon.icns"
SVG_PATH = REPO_ROOT / "assets" / "app-icon.svg"
TRAY_ICONS_DIR = REPO_ROOT / "host" / "clawd_tank_menubar" / "icons"

CRAB_W, CRAB_H = 15, 9

# (x, y, w, h) in crab grid coordinates: clawd-static-base.svg rects with the
# y axis shifted up by 6 (the crab starts at row 6 of the 15x16 viewBox).
BODY_RECTS = [
    (2, 0, 11, 7),   # torso
    (0, 3, 2, 2),    # left arm
    (13, 3, 2, 2),   # right arm
    (3, 7, 1, 2),    # legs
    (5, 7, 1, 2),
    (9, 7, 1, 2),
    (11, 7, 1, 2),
]
EYE_RECTS = [
    (4, 2, 1, 2),
    (10, 2, 1, 2),
]

BODY_COLOR = "#DE886D"
EYE_COLOR = "#000000"
BACKGROUND_COLOR = "#1b1b1f"
CORNER_RADIUS = 0.22      # fraction of the icon size
CRAB_WIDTH_FRACTION = 0.70
CRAB_DROP = 0.03          # crab sits slightly below center, fraction of size
SUPERSAMPLE = 4           # background corners are antialiased by supersampling

# (filename stem, pixel size) — the exact set the iconset carries.
ICONSET_SIZES = [
    ("icon_16x16", 16), ("icon_16x16@2x", 32),
    ("icon_32x32", 32), ("icon_32x32@2x", 64),
    ("icon_128x128", 128), ("icon_128x128@2x", 256),
    ("icon_256x256", 256), ("icon_256x256@2x", 512),
    ("icon_512x512", 512), ("icon_512x512@2x", 1024),
]
ICNS_SIZES = [16, 32, 64, 128, 256, 512, 1024]

TRAY_SIZE = 32
TRAY_SCALE = 2
TRAY_VARIANTS = {
    "win-crab-disconnected": ("#8a8a8a", "#303030", False),
    "win-crab-connected": (BODY_COLOR, EYE_COLOR, False),
    "win-crab-notifications": (BODY_COLOR, EYE_COLOR, True),
}
BADGE_COLOR = "#E53E3E"
BADGE_BOX = (22, 0, 31, 9)    # 10x10 disc in the top-right corner
BADGE_GAP = 1                 # transparent ring separating badge from crab


def crab_layout(size: int) -> tuple[int, int, int]:
    """Return (scale, x0, y0): the largest integer scale whose crab fits
    CRAB_WIDTH_FRACTION of the width, centered and dropped slightly."""
    scale = max(1, int(size * CRAB_WIDTH_FRACTION) // CRAB_W)
    x0 = (size - CRAB_W * scale) // 2
    y0 = (size - CRAB_H * scale) // 2 + round(size * CRAB_DROP)
    y0 = min(y0, size - CRAB_H * scale)
    return scale, x0, y0


def draw_crab(img: Image.Image, scale: int, x0: int, y0: int,
              body: str, eyes: str) -> None:
    draw = ImageDraw.Draw(img)
    for rects, color in ((BODY_RECTS, body), (EYE_RECTS, eyes)):
        for x, y, w, h in rects:
            draw.rectangle(
                (x0 + x * scale, y0 + y * scale,
                 x0 + (x + w) * scale - 1, y0 + (y + h) * scale - 1),
                fill=color,
            )


def render_app_icon(size: int) -> Image.Image:
    big = Image.new("RGBA", (size * SUPERSAMPLE,) * 2, (0, 0, 0, 0))
    ImageDraw.Draw(big).rounded_rectangle(
        (0, 0, size * SUPERSAMPLE - 1, size * SUPERSAMPLE - 1),
        radius=round(size * SUPERSAMPLE * CORNER_RADIUS),
        fill=BACKGROUND_COLOR,
    )
    img = big.resize((size, size), Image.LANCZOS)
    draw_crab(img, *crab_layout(size), BODY_COLOR, EYE_COLOR)
    return img


def render_app_icon_svg(size: int = 1024) -> str:
    scale, x0, y0 = crab_layout(size)

    def rect(x, y, w, h):
        return (f'        <rect x="{x0 + x * scale}" y="{y0 + y * scale}" '
                f'width="{w * scale}" height="{h * scale}"/>')

    lines = [
        f'<svg viewBox="0 0 {size} {size}" xmlns="http://www.w3.org/2000/svg">',
        "    <!-- Generated by tools/gen_app_icons.py; edit the generator, not this file. -->",
        f'    <rect x="0" y="0" width="{size}" height="{size}" '
        f'rx="{round(size * CORNER_RADIUS)}" fill="{BACKGROUND_COLOR}"/>',
        f'    <g fill="{BODY_COLOR}" shape-rendering="crispEdges">',
        *(rect(*r) for r in BODY_RECTS),
        "    </g>",
        f'    <g fill="{EYE_COLOR}" shape-rendering="crispEdges">',
        *(rect(*r) for r in EYE_RECTS),
        "    </g>",
        "</svg>",
        "",
    ]
    return "\n".join(lines)


def render_tray_icon(body: str, eyes: str, badge: bool) -> Image.Image:
    img = Image.new("RGBA", (TRAY_SIZE, TRAY_SIZE), (0, 0, 0, 0))
    x0 = (TRAY_SIZE - CRAB_W * TRAY_SCALE) // 2
    y0 = (TRAY_SIZE - CRAB_H * TRAY_SCALE) // 2
    draw_crab(img, TRAY_SCALE, x0, y0, body, eyes)
    if badge:
        draw = ImageDraw.Draw(img)
        left, top, right, bottom = BADGE_BOX
        draw.ellipse((left - BADGE_GAP, top - BADGE_GAP,
                      right + BADGE_GAP, bottom + BADGE_GAP), fill=(0, 0, 0, 0))
        draw.ellipse(BADGE_BOX, fill=BADGE_COLOR)
    return img


def main():
    for stem, size in ICONSET_SIZES:
        render_app_icon(size).save(ICONSET_DIR / f"{stem}.png")
        print(f"  {stem}.png ({size}x{size})")

    renders = {size: render_app_icon(size) for size in ICNS_SIZES}
    renders[1024].save(ICNS_PATH, append_images=[renders[s] for s in ICNS_SIZES[:-1]])
    print(f"  {ICNS_PATH.name}")

    SVG_PATH.write_text(render_app_icon_svg(), encoding="utf-8", newline="\n")
    print(f"  {SVG_PATH.name}")

    for name, (body, eyes, badge) in TRAY_VARIANTS.items():
        render_tray_icon(body, eyes, badge).save(TRAY_ICONS_DIR / f"{name}.png")
        print(f"  {name}.png ({TRAY_SIZE}x{TRAY_SIZE})")


if __name__ == "__main__":
    main()
